---
- name: Download a file from GitHub to the remote server
  hosts: app
  become: true
  tasks:
    - name: Ensure /opt/downloads directory exists
      file:
        path: /opt/downloads
        state: directory
        owner: kristian
        group: kristian
        mode: '0755'

    - name: Download ping_all.yml from GitHub
      get_url:
        url: https://github.com/krisgeorgiev/devops-labs/blob/main/ansible/playbooks/ping_all.yml
        dest: /opt/downloads/ping_all.yml
        owner: kristian
        group: kristian
        mode: '0644'
