network:
  version: 2
  ethernets:
    eth0:
      dhcp4: no
      addresses: [192.168.56.10/24]
      nameservers:
        addresses: [1.1.1.1, 8.8.8.8]
      routes:
        - to: 0.0.0.0/0
          via: 192.168.56.1
